version: '3.9'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/restaurant_db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: