"""Migración inicial

Revision ID: 87bedc6ad236
Revises: 
Create Date: 2025-06-25 20:26:17.568185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bedc6ad236'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cliente', sa.String(length=100), nullable=False),
        sa.Column('direccion', sa.String(length=200), nullable=False),
        sa.Column('metodo_pago', sa.String(length=50), nullable=False),
        sa.Column('producto_nombre', sa.String(length=100), nullable=True),
        sa.Column('producto_precio', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('total_precio', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('estado', sa.String(length=50), nullable=True),
        sa.Column('creado_en', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False, server_default='SIN_APELLIDO'))
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=False, server_default='SIN_DIRECCION'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('apellido')

    op.drop_table('pedidos')
    # ### end Alembic commands ###